apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  externalIPs:
    - "192.168.1.101"
  ports:
  - port: 8081
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
